// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Read health",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Read health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Health"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs": {
            "post": {
                "description": "Create a new job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Create job",
                "parameters": [
                    {
                        "description": "Job to create",
                        "name": "job",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Job"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Job"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/local-queues": {
            "get": {
                "description": "Get local queues",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LocalQueues"
                ],
                "summary": "Get local queues",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.LocalQueue"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/namespaces/{namespace}/local-queues": {
            "post": {
                "description": "Create a new local queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LocalQueues"
                ],
                "summary": "Create local queue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LocalQueue namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "LocalQueue to create",
                        "name": "localQueue",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LocalQueue"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.LocalQueue"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/namespaces/{namespace}/local-queues/{name}": {
            "get": {
                "description": "Get local queue detail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LocalQueues"
                ],
                "summary": "Get local queue detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LocalQueue namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "LocalQueue name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LocalQueue"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a local queue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LocalQueues"
                ],
                "summary": "Delete local queue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LocalQueue namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "LocalQueue name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/nodes": {
            "get": {
                "description": "Get nodes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nodes"
                ],
                "summary": "Get nodes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Node"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/nodes/{name}": {
            "get": {
                "description": "Get node detail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nodes"
                ],
                "summary": "Get node detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.NodeDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/pods": {
            "get": {
                "description": "Get pods",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pods"
                ],
                "summary": "Get pods",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Pod"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/pods/{namespace}/{name}": {
            "get": {
                "description": "Get pod detail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pods"
                ],
                "summary": "Get pod detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pod namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pod name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PodDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/resource-flavors": {
            "get": {
                "description": "Get resource flavors",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ResourceFlavors"
                ],
                "summary": "Get resource flavors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ResourceFlavor"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new resource flavor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ResourceFlavors"
                ],
                "summary": "Create resource flavor",
                "parameters": [
                    {
                        "description": "ResourceFlavor to create",
                        "name": "resourceFlavor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResourceFlavor"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ResourceFlavor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/resource-flavors/{name}": {
            "get": {
                "description": "Get resource flavor detail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ResourceFlavors"
                ],
                "summary": "Get resource flavor detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ResourceFlavor name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResourceFlavor"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a resource flavor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ResourceFlavors"
                ],
                "summary": "Delete resource flavor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ResourceFlavor name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Condition": {
            "type": "object",
            "properties": {
                "lastTransitionTime": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "observedGeneration": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.ContainerPort": {
            "type": "object",
            "properties": {
                "containerPort": {
                    "type": "integer"
                },
                "hostIP": {
                    "type": "string"
                },
                "hostPort": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                }
            }
        },
        "models.EnvVar": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "models.FlavorUsage": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ResourceUsage"
                    }
                }
            }
        },
        "models.Health": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "models.Job": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "models.LocalQueue": {
            "type": "object",
            "properties": {
                "admittedWorkloads": {
                    "type": "integer"
                },
                "clusterQueue": {
                    "type": "string"
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Condition"
                    }
                },
                "flavorsReservation": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FlavorUsage"
                    }
                },
                "flavorsUsage": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FlavorUsage"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "pendingWorkloads": {
                    "type": "integer"
                },
                "reservingWorkloads": {
                    "type": "integer"
                },
                "stopPolicy": {
                    "type": "string"
                }
            }
        },
        "models.Node": {
            "type": "object",
            "properties": {
                "cpu": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "kubeletVersion": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ready": {
                    "type": "boolean"
                },
                "roles": {
                    "type": "string"
                }
            }
        },
        "models.NodeAddress": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.NodeCondition": {
            "type": "object",
            "properties": {
                "lastHeartbeatTime": {
                    "type": "string"
                },
                "lastTransitionTime": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.NodeDetail": {
            "type": "object",
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NodeAddress"
                    }
                },
                "allocatable": {
                    "$ref": "#/definitions/models.NodeResources"
                },
                "annotations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "capacity": {
                    "$ref": "#/definitions/models.NodeResources"
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NodeCondition"
                    }
                },
                "creationTimestamp": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NodeImage"
                    }
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "nodeInfo": {
                    "$ref": "#/definitions/models.NodeSystemInfo"
                },
                "podCIDR": {
                    "type": "string"
                },
                "ready": {
                    "type": "boolean"
                },
                "roles": {
                    "type": "string"
                },
                "taints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NodeTaint"
                    }
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.NodeImage": {
            "type": "object",
            "properties": {
                "names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sizeBytes": {
                    "type": "integer"
                }
            }
        },
        "models.NodeResources": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "models.NodeSystemInfo": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string"
                },
                "bootID": {
                    "type": "string"
                },
                "containerRuntimeVersion": {
                    "type": "string"
                },
                "kernelVersion": {
                    "type": "string"
                },
                "kubeProxyVersion": {
                    "type": "string"
                },
                "kubeletVersion": {
                    "type": "string"
                },
                "machineID": {
                    "type": "string"
                },
                "operatingSystem": {
                    "type": "string"
                },
                "osImage": {
                    "type": "string"
                },
                "systemUUID": {
                    "type": "string"
                }
            }
        },
        "models.NodeTaint": {
            "type": "object",
            "properties": {
                "effect": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "timeAdded": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.OwnerReference": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.Pod": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "node": {
                    "type": "string"
                },
                "podIP": {
                    "type": "string"
                },
                "restarts": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "statusClass": {
                    "type": "string"
                }
            }
        },
        "models.PodCondition": {
            "type": "object",
            "properties": {
                "lastProbeTime": {
                    "type": "string"
                },
                "lastTransitionTime": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.PodContainer": {
            "type": "object",
            "properties": {
                "env": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EnvVar"
                    }
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ContainerPort"
                    }
                },
                "ready": {
                    "type": "boolean"
                },
                "resources": {
                    "$ref": "#/definitions/models.ResourceRequirements"
                },
                "restartCount": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "stateReason": {
                    "type": "string"
                },
                "volumeMounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.VolumeMount"
                    }
                }
            }
        },
        "models.PodDetail": {
            "type": "object",
            "properties": {
                "annotations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PodCondition"
                    }
                },
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PodContainer"
                    }
                },
                "creationTimestamp": {
                    "type": "string"
                },
                "hostIP": {
                    "type": "string"
                },
                "initContainers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PodContainer"
                    }
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "node": {
                    "type": "string"
                },
                "ownerReferences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OwnerReference"
                    }
                },
                "podIP": {
                    "type": "string"
                },
                "qosClass": {
                    "type": "string"
                },
                "serviceAccount": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "statusClass": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "volumes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PodVolume"
                    }
                }
            }
        },
        "models.PodVolume": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.ResourceFlavor": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "nodeLabels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "nodeTaints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NodeTaint"
                    }
                },
                "tolerations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Toleration"
                    }
                },
                "topologyName": {
                    "type": "string"
                }
            }
        },
        "models.ResourceRequirements": {
            "type": "object",
            "properties": {
                "limits": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "requests": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ResourceUsage": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "total": {
                    "type": "string"
                }
            }
        },
        "models.Toleration": {
            "type": "object",
            "properties": {
                "effect": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "tolerationSeconds": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.VolumeMount": {
            "type": "object",
            "properties": {
                "mountPath": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "readOnly": {
                    "type": "boolean"
                },
                "subPath": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
